### ISSUE TITLE
Power Law Inplementation

### ISSUE THREAD

**Issue by imanring** [fcheysson/hawkesbow#1]
There is numerical instability with the density of power law.
dpowerlaw(1,shape = 143.8691,scale = 135.2293) = Inf
Maybe using log in the implementation could help.

**Comment by fcheysson** [comment]
Indeed, my implementation of dpowerlaw was not optimal (it already used the log in the implementation, but in a rather naive way). This should be corrected in the most recent commit.
However, I'm intrigued by the order of magnitude of the parameters in your power law distribution: the power law is usually used with a small-ish shape, to model distributions with some infinite moments (typically extreme values). Here, the shape you specify seems extremely high, which might indicate that the power law might not be fit to modelise your data.
If the shape and scale are a result of optimising the Hawkes process with respect to these two parameters, know that the two estimators are strongly correlated, and that the optimisation algorithm has difficulty finding the correct parameters. You might get better results with another distribution, or by fixing the scale or the shape (whichever you could have some a priori information about).
Best regards.

**Comment by imanring** [comment]
The results were from the optimization. I've been playing around with different kernels. I think that the exponential may be a better choice. Thanks for the advice.
